import { Opportunity } from "./pages/VolunteerBoardPage";

// export const volunteerOpportunities: Opportunity[] = [
//     {
//       ID: 1,
//       name: "Park Cleanup",
//       description: "Help us clean up the local park and make it a better place for everyone.",
//       company: "Green Earth",
//       location: "New York, NY",
//       date: "2023-05-10",
//       volunteersNeeded: 20,
//       duration: "3 hours",
//     },
//     {
//       id: 2,
//       name: "Food Bank Support",
//       description: "Assist in packing and distributing food to those in need at our local food bank.",
//       company: "Helping Hands",
//       location: "Los Angeles, CA",
//       date: "2023-05-20",
//       volunteersNeeded: 15,
//       duration: "4 hours",
//     },
//     {
//       id: 3,
//       name: "Beach Cleanup",
//       description: "Help us keep the beach clean and protect marine life.",
//       company: "Ocean Conservancy",
//       location: "Miami, FL",
//       date: "2023-06-05",
//       volunteersNeeded: 30,
//       duration: "2 hours",
//     },
//     {
//       ID: 4,
//       name: "Tutoring",
//       description: "Help students improve their academic performance by providing one-on-one tutoring.",
//       company: "Education First",
//       location: "Chicago, IL",
//       date: "2023-06-10",
//       volunteersNeeded: 10,
//       duration: "2 hours",
//     },
//     {
//       ID: 5,
//       name: "Animal Shelter Support",
//       description: "Assist in taking care of animals at our local animal shelter.",
//       company: "Humane Society",
//       location: "San Francisco, CA",
//       date: "2023-06-15",
//       volunteersNeeded: 5,
//       duration: "3 hours",
//     },
//     {
//       id: 6,
//       name: "Community Garden",
//       description: "Help us maintain and improve our community garden.",
//       company: "Urban Farming",
//       location: "Portland, OR",
//       date: "2023-06-25",
//       volunteersNeeded: 8,
//       duration: "4 hours",
//     },
//     {
//       id: 7,
//       name: "Street Cleaning",
//       description: "Help us clean the streets and make our city more beautiful.",
//       company: "City Services",
//       location: "New Orleans, LA",
//       date: "2023-07-05",
//       volunteersNeeded: 15,
//       duration: "3 hours",
//     },
//     {
//       id: 8,
//       name: "Habitat for Humanity",
//       description: "Help us build affordable homes for those in need.",
//       company: "Habitat for Humanity",
//       location: "Denver, CO",
//       date: "2023-07-10",
//       volunteersNeeded: 20,
//       duration: "6 hours",
//     },
//     {
//       id: 9,
//       name: "Community Cleanup",
//       description: "Help us clean up the streets, parks, and public spaces in our community.",
//       company: "Community Services",
//       location: "Seattle, WA",
//       date: "2023-07-20",
//       volunteersNeeded: 25,
//       duration: "4 hours",
//     }
// ];
  